### ISSUE TITLE
IntelliSense does not include current section member's name

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/powerquery-language-services#109]
When typing up the following expression:
````
section Section1;

shared A = @A; // for simplicity's sake; for a real life example, pretend that A is a recursive function 
shared B = A;
````

IntelliSense for B's expression correctly includes identifier A in the list of options provided; however, the IntelliSense for A's expression does not include itself, even when using an inclusive identifier reference (`@A`).

Seems like A's IntelliSence should include itself, at least when an @-reference is being used.

**Comment by JordanBoltonMN** [comment]
Yeah, recursive identifiers are not fully implemented yet. I currently don't have it on the roadmap. partly because they seem to be rather infrequently used compared to higher priority Intellisense items. It's still something I intend to work on one of these days :)

**Comment by JordanBoltonMN** [comment]
Resolved with... some old PR. I forgot to close this out when I did.
