### ISSUE TITLE
[Validation] report duplicate function parameters

### ISSUE THREAD

**Issue by mattmasson** [microsoft/powerquery-language-services#18]
#16 adds duplicate identifier warnings, but doesn't cover duplicate function parameters. 

![image](https://user-images.githubusercontent.com/5509937/86932823-d6bf1400-c107-11ea-9cd6-eb17a2f21b89.png)

**Comment by JordanBoltonMN** [comment]
@mattmasson I know this is existing SDK behavior, but how important is this if we're already validating the number of arguments and if their types match?

**Comment by JordanBoltonMN** [comment]
> @mattmasson I know this is existing SDK behavior, but how important is this if we're already validating the number of arguments and if their types match?

Never mind. I was misreading this as a InvokeExpression issue, not as a FunctionExpression issue.
