### ISSUE TITLE
Don't send completion items when on lefthand side of variable declaration

### ISSUE THREAD

**Issue by mattmasson** [microsoft/powerquery-language-services#23]
If we're expecting an identifier constant (i.e. lefthand side of variable declaration), we shouldn't return completion items. 

`let a = 1,|`

**Comment by JordanBoltonMN** [comment]
A few changes have happened.
* The parser was updated so it correctly doesn't supply autocomplete values when in a field name.
* A temporary work around with primitive type constants was made which now _always_ supplies those constants.
* The parser was updated so it properly supplies primitive constants.

So now the remaining step is to remove the temporary work around then we should be good.
